# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Generate iCalendar

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 */1 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: ics
        run: |
          git checkout actions
          git merge origin/main --no-edit
          git config user.name github-actions
          git config user.email github-actions@github.com
          python main.py
          git add .
          git commit -m "calendar update"
          git push
